
services:
 
  mongodb:
    image: mongo:5
    container_name: fintechforge_mongodb
    restart: unless-stopped
    ports:
      - "${MONGO_PORT:-27017}:27017"
    command: ["mongod", "--replSet", "rs0"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME:-root}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD:-example}"
    healthcheck:
      test: ["CMD-SHELL", "mongo --quiet --eval \"db.runCommand({ ping: 1 }).ok\" mongodb:27017/test || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Node.js backend (backend-node)
  backend-node:
    build:
      context: ./backend-node
      dockerfile: Dockerfile
    container_name: fintechforge_backend_node
    env_file:
      - ./backend-node/.env.example
    environment:
      NODE_ENV: "${BACKEND_NODE_ENV:-development}"
      PORT: "${BACKEND_NODE_PORT:-3000}"
      MONGO_URL: "${MONGO_URL:-mongodb://mongodb:${MONGO_PORT:-27017}/fintechforge}"
    
    ports:
      - "${BACKEND_NODE_PORT:-3000}:${BACKEND_NODE_PORT:-3000}"
    depends_on:
      mongodb:
        condition: service_healthy
    

  # Python backend (backend-python)
  backend-python:
    build:
      context: ./backend-python
      dockerfile: Dockerfile
    container_name: fintechforge_backend_python
    env_file:
      - ./backend-python/.env.example
    environment:
      PYTHON_ENV: "${BACKEND_PYTHON_ENV:-development}"
      PORT: "${BACKEND_PYTHON_PORT:-8000}"
      MONGO_URL: "${MONGO_URL:-mongodb://mongodb:${MONGO_PORT:-27017}/fintechforge}"
    ports:
      - "${BACKEND_PYTHON_PORT:-8000}:${BACKEND_PYTHON_PORT:-8000}"
    depends_on:
      mongodb:
        condition: service_healthy
    

  # Frontend (React/Vite)
  frontend-react:
    build:
      context: ./frontend-react
      dockerfile: Dockerfile
    container_name: fintechforge_frontend
    env_file:
      - ./frontend-react/.env.example
    environment:

      REACT_APP_API_URL: "${REACT_APP_API_URL:-http://localhost:${BACKEND_NODE_PORT:-3000}}"
      PORT: "${FRONTEND_PORT:-3001}"
    ports:
      - "${FRONTEND_PORT:-3001}:${FRONTEND_PORT:-3001}"
    depends_on:
      - backend-node
      - backend-python


