name: Lint and Format Check

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  lint-and-format:
    name: ESLint & Prettier Check
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: frontend-react/package-lock.json

      - name: Install dependencies
        working-directory: ./frontend-react
        run: npm ci

      - name: Run ESLint
        working-directory: ./frontend-react
        run: npm run lint

      - name: Check formatting with Prettier
        working-directory: ./frontend-react
        run: npm run format:check

      - name: Type check
        working-directory: ./frontend-react
        run: npm run type-check

      - name: Build project
        working-directory: ./frontend-react
        run: npm run build
